### ISSUE TITLE
[EXPIRED] Pale Moon support

### ISSUE THREAD

**Issue by sergeevabc** [cheeaun/max-tabs#26]
Dear Lim Chee Aun, could you be so kind to explore the possibility of making Max Tabs compatible with Palemoon (which is an optimized fork of Firefox ESR 24)?

**Comment by cheeaun** [comment]
@sergeevabc so it's not working now? I haven't try Palemoon before so just wondering what kind of errors do you see.

**Comment by sergeevabc** [comment]
@cheeaun, current implementation of Max Tabs is based on Jetpack, while [Palemoon welcomes XUL](https://tldrify.com/kk4).
